#!MCVM cd ${mdir} && cmake -Bbuild -Cmcvm.cmake --fresh && cmake --build build
set(CMAKE_CXX_COMPILER clang++ CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER clang CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "Ninja Multi-Config" CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS 1 CACHE STRING "" FORCE)
list(APPEND COMPILER_FLAGS
  -fcolor-diagnostics
)
list(APPEND LINKER_FLAGS
  -Wl,--color-diagnostics
  # -Wl,--thinlto-cache-dir=.cache/lto
)
string(REPLACE ";" " " COMPILER_FLAGS "${COMPILER_FLAGS}")
string(REPLACE ";" " " LINKER_FLAGS "${LINKER_FLAGS}")

set(CMAKE_C_FLAGS_INIT ${COMPILER_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT ${COMPILER_FLAGS} CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_INIT ${LINKER_FLAGS} CACHE STRING "" FORCE)

set(CMAKE_COLOR_DIAGNOSTICS 1 CACHE STRING "" FORCE)
# set(CMAKE_INSTALL_PREFIX /home/mcvm/install CACHE STRING "" FORCE)
set(CMAKE_BUILD_TYPE Debug CACHE STRING "" FORCE)
# set(CMAKE_VERBOSE_MAKEFILE 1 CACHE STRING "" FORCE)
# set(CMAKE_FIND_DEBUG_MODE 1 CACHE STRING "" FORCE)

# set(X11_INC_SEARCH_PATH /usr/include CACHE STRING "" FORCE)
# set(X11_LIB_SEARCH_PATH /usr/lib CACHE STRING "" FORCE)

